### ISSUE TITLE
Don't mention Gtk+ in your app description

### ISSUE THREAD

**Issue by danrabbit** [BharatKalluri/Easypass#12]
https://github.com/BharatKalluri/Easypass/blob/f47579b70f21e6fc5623499220811feeed61cb20/data/com.github.bharatkalluri.easypass.appdata.xml#L12

Since all apps in AppCenter are Gtk+, this doesn't tell potential users anything unique about your app

**Comment by BharatKalluri** [comment]
True, Fixed it @danrabbit , just wanted your opinion, what do you think of the app's design. Can I do anything to improve the application?

**Comment by danrabbit** [comment]
That's a pretty open ended question! I think every app probably has room for improvements. Our work is never done :) But, I'm not a keepass user myself, so I probably won't have super valuable input on this particular app.
