### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by arshubham** [BharatKalluri/Easypass#14]
It is not yet in appcenter so I installed it from source but getting error on launch.

> Traceback (most recent call last):
  File "/usr/local/bin/com.github.bharatkalluri.easypass", line 4, in <module>
    from easypass.main import Application
  File "/usr/local/lib/python3.5/dist-packages/easypass/main.py", line 6, in <module>
    import easypass.window as wn
  File "/usr/local/lib/python3.5/dist-packages/easypass/window.py", line 7, in <module>
    import easypass.headerbar as hb
  File "/usr/local/lib/python3.5/dist-packages/easypass/headerbar.py", line 8, in <module>
    import easypass.db as db
  File "/usr/local/lib/python3.5/dist-packages/easypass/db.py", line 1, in <module>
    from pykeepass import PyKeePass
ImportError: No module named 'pykeepass'

Am I missing any dependencies?

**Comment by BharatKalluri** [comment]
Yeah,
```bash
pip3 install pykeepass
```

**Comment by arshubham** [comment]
Same error when using deb from http://packages.elementary.io/testing/pool/main/c/com.github.bharatkalluri.easypass/

and  I looked for _pykeepass_ in repos, it isn't there.

**Comment by arshubham** [comment]
Shouldn't it be bundled with deb? :)

**Comment by BharatKalluri** [comment]
Yes, it should be. It was installed in my system all along, so I forgot about including it. Thanks for reporting!

**Comment by BharatKalluri** [comment]
Hey @arshubham ,
Try removing pykeepass by doing
```
pip3 uninstall pykeepass
```
and try to install again. this time it should download pykeepass itself(hopefully). If that works we can close this issue!

**Comment by arshubham** [comment]
Busy now. But will test and report in a few hours.

**Comment by arshubham** [comment]
Compiling from code works 👍 . Will have to wait till a deb is released  to test.
